CONTRIBUTING.md
- put contribution to code first, requests second (diff is therefore unreadable, sorry😥)
- tried to slightly rephrased the notes about licenses, as they didn't fully parse for me (Please review and fix if needed, thanks!🙏🏽)
- TODO: more details on how to get started contributing?
=> Slightly restructured the CONTRIBUTING.md

js/tree-edam-stand-alone.js
**Issue:** #47 
**Before:**
**After:**
=> fix: duplicate parents bug #47

CONTRIBUTING.md
Feel free to improve @hmenager
=> Indicate to do one PR per issue

css/index.css, index.html
Added the available means of communication between the developer community, user and the project maintainer.
=> Communication logos added

js/tree-edam-stand-alone.js
#46 
@matuskalas I'm updating for those only for which I don't need to look for a better approach as suggested by @bryan-brancotte 
For the rests elements I'll create other PR on 8th April when I'll get some more time to work :)
So, this can be merged so that other assignee can work properly, may be by taking some reference from this PR.
=> Tooltips added for bio.tools, Biosphere, BioWeb & TeSS

css/index.css
=> Fixing positioning issues for mobile

css/index.css
As indicated by @bryan-brancotte in #85, I have added the CSS without changing its format!
=> Changed Cursor from text to pointer in dropdown menu!

css/index.css, index.html
Following work done in #68 I wanted to re-use map button appearance, here after is a proposition
Note that pointer is over the expanded link. Icon might need improvement, but I don't want to spend time on drawing my own svg icon, for now.
pinging @HagerDakroury and @hmenager from #89 and @Gladyzz  from #63 if you want to give you view on this PR
=> Tree controls vertical

js/tree-reusable-d3.js
A fix to a typo in the comments.
=> fixing a comment mismatch

css/index.css, index.html, js/tree-edam-stand-alone.js
=> Removed 'previously seen' title when not required!

css/tree-reusable-d3.css
**Fixes issue:** #90 
This will look more consistent after #105 gets fixed.
**Before:**
**After:**
=> Changing tree text cursor to pointer

css/index.css
=> Enhancing the UI of details section!

README.md, edit.html
Minor change
Following [this](https://github.com/edamontology/edam-browser/commit/99428cf9a3ed5dc51844a79f50f71979e6798f9e#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051) & [this](https://github.com/edamontology/edam-browser/pull/62#discussion_r606208426) updation.
Updated the font awesome version for the propose change pages too. and then updated in the readme. So that it can be same everywhere.
=> Fontawesome version update

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
=> Modified PR Template added

js/tree-edam-stand-alone.js
Regarding Issue #81, I replaced the popup from the right side to the left side!
Before:
After:
=> Relocate the popup box to make content fully visible!

css/dark-theme.css, index.html
This PR improves theme button in terms of position and appearance
=> improve theme buton

css/index.css, index.html, js/index.js
close #161 
https://user-images.githubusercontent.com/45493793/116724585-771b5780-a9fe-11eb-832d-bce917df5c11.mp4
@bryan-brancotte Please check.
=> Loader animation

edit.html
close #103
Can be seen live [here](https://raashika03.github.io/edam-browser/#data_0006)
Before:
After:
=> fixed edit page alignment on using input box

index.html
=> Improve visibility of search icon

css/dark-theme.css
=> minor bg-colour change for search icon for dark-theme

edit.html, js/edit.js
=> #50 Showing relevant terms in term creation form

.github/user_feedback_template.md
This request closes #131 if its okay with @bryan-brancotte
=> add user feedback issue template

css/index.css, js/tree-reusable-d3.js
resolve #69   
closes #105
works in Firefox and Chrome
=> add visual effect when dragging the tree

css/index.css
closes #105 
Tested on chrome and firefox
=> feat(tree):Add grabbing cursor when dragging

js/tree-edam-stand-alone.js
The link+btn snippet added to the sources
=> Link n btn to cpy

js/tree-reusable-d3.js
=> fix: Make tooltip responsive

css/index.css, index.html, js/index.js, js/tree-edam-stand-alone.js
The way to store settings was not pleasant on code side, here is it easier
=> Auto save settings

edit.html, js/edit.js, js/tree-edam-stand-alone.js
=> #176 Added 'Is Identifier Of' term relationship in the edit form

index.html, js/tree-edam-stand-alone.js
Related to https://github.com/edamontology/edamontology/issues/682
It use the value when provided, no impact for now, but used with latest
=> Use more meta info

js/tree-reusable-d3.js
solve https://github.com/edamontology/edam-browser/pull/222#pullrequestreview-717833021
=> use the first child of the root node, or the root itself

index.html, js/tree-edam-stand-alone.js, js/tree-reusable-d3.js, package.json
related-to #226 
1. Cleaned and commented loadTree code and removed redundant code
2. Added error handling when loading a custom version
3. Added form validation (to detect wrong format)
=> feat: Add error handling/form validation to custom version
